server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  redis:
    password: Rrr241356@
    cluster:
      max-redirects: 3
      nodes:
        - 47.113.216.8:6382
        - 47.113.216.8:6383
        - 47.113.216.8:6384
        - 47.113.216.8:6385
        - 47.113.216.8:6386
        - 47.113.216.8:6387
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
